# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     AboutCannabis.Repo.insert!(%SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias AboutCannabis.Repo
alias AboutCannabis.Article

Repo.insert!(%Article{title: "MICHIGAN COURT RULES AGAINST MEDICAL MARIJUANA PATIENTS SMOKING IN CARS", body: "The Michigan Court of Appeals ruled that the medical marijuana laws in the Wolverine State do not offer legal protection for patients who consume cannabis in their personal vehicles. Following a 2-1 vote in Lansing, a precedent has been set dictating that registered medical marijuana patients cannot smoke cannabis while parked in their own car outside of a private business.\nThis ruling came after Robert Carlton was arrested for smoking medical marijuana inside his car in the parking of a Mt. Pleasant Casino. Carlton and his attorney contended that his vehicle is not open to the public and therefore he should be free from legal prosecution. Judges at the circuit and district levels agreed with this argument.\nUnlike the circuit and district judges, the Court of Appeals judges did not side in favor of Carlton. They decided that although Carlton was inside of his vehicle at the time, it was parked in a public place which cancelled out the immunity extended to registered medical marijuana patients under the law.", slug: "michigan-court-rules-against-medical-marijuana-patients-smoking-in-cars", source: "https://www.whaxy.com/news/can-michigan-medical-marijuana-patients-smoke-in-cars", media: "@whaxy", author: "Connor Bland", email: "connor.bland@gmail.com", is_draft: false, is_public: true})

Repo.insert!(%Article{title: "STEVIE WONDER CANNABIS STRAIN REVIEW", body: "I peered through a glass display case protecting cannabis at Denver’s Pure Marijuana Dispensary on Bannock Street; Stevie Wonder peered back at me as I asked myself, “how do strains get their names?”\nMoments before, I was waiting in Pure’s oddly soothing, Easter-colored waiting room enjoying some semi-obscure hip hop. At that time, my only concern was “I want the good stuff.” The always-friendly receptionist with a necktie collection that would make Craig Sager blush—this time sporting a red, patterned number—called me into the sales area.\n<img src='http://www.whaxy.com/wp-content/uploads/2015/11/stevie-wonder-marijuana.jpg'>\nOnce I began inspecting the cannabis on display, my focus quickly shifted to Stevie Wonder—an affordable sativa cannabis strain.", slug: "stevie-wonder-cannabis-strain-review", source: "https://www.whaxy.com/news/stevie-wonder-strain-review", media: "@whaxy", author: "Yar Malezzy", email: "malezzy.cz@gmail.com", is_draft: false, is_public: true})


Repo.insert!(%Article{title: "PUBLIC MEDICAL MARIJUANA CONSUMPTION NOW PERMITTED IN ONTARIO", body: "Contrary to Canada’s strict policies against public tobacco use, a new law in Ontario allows medical marijuana patients to smoke and vape cannabis in any public place, as long as the establishment does not have a liquor license.\n Certified medical marijuana patients in Ontario are no longer subject to the same laws that govern smoking and vaping tobacco in public places, announced Associate Minister of Health and Long-Term Care, Dipika Damerla. Tobacco and cannabis smoke have officially been separated by law.\n
“The law allows for an exemption because someone needs it for a medical purpose,”\n he explained.\n The same law that permits medical marijuana patients the freedom to consume also grants business owners and employers the right to override the freedom. “As an employer and a restaurant owner, you can say that there is no vaping, no smoking of medical marijuana,” Damerla said. Damerla also clarified that the law does permit both smoking and vaporizing, as long as the patient has a doctor’s recommendation for it.\n While medical marijuana advocates commend the freedom provided by the new law, Patrick Brown, Ontario PC Leader, worries that the new law may challenge municipal guidelines that are already in place. “The conversation they should have is with municipalities to make sure that the provincial regulations are in line with what municipalities have already established,” he said. “And in some cases they have their own regulations that prohibit smoking in places like parks.”\n Brown was not concerned, however, that patients will use the new law as an opportunity to smoke cannabis around children, explaining that he doubts there will be “an overwhelming amount of people in Ontario running out to parks to have their medical marijuana.”\n Andrea Horwath, NDP Leader commented that her party would further investigate the new rules regarding the public consumption of medical marijuana.\n “We know that Health Canada has issued some warnings about exposure of young people to the smoke and vapor of medical marijuana and that’s something we have to keep in mind,”\n aid Horwarth.\n Jonathan Zaid, Founder and Executive Director of Canadians for Fair Access to Medical Marijuana (CFAMM) stated: “This is another important milestone in the recognition of the legitimacy of the use of cannabis as a medicine. Ontario has taken a huge step forward by exempting medical cannabis patients and their use of vaporizers.”", slug: "ontario-permits-public-medical-marijuana-consumption", source: "https://www.whaxy.com/news/ontario-permits-public-medical-marijuana-consumption", media: "@whaxy", author: "Yar Malezzy", email: "malezzy.cz@gmail.com", is_draft: false, is_public: true})

Repo.insert!(%Article{title: "THE LOUD CHALLENGE: SMOKE WEED IN PUBLIC", body: "A new online challenge has marijuana users lighting up on camera in public. The goal of the challenge is to smoke weed in at the most absurd of public locations and catch it on film, all without being nabbed by security. Whether it’s on the bus, in the airport or at the local shopping mall, smokers are starting to light up to get their few minutes of Youtube fame. Urban dictionary site’s smokin’ loud as high grade marijuana, but this challenge has smoker’s lighting up that high grade in places like Walmart. Similar to the ice bucket challenge, the social aspect of this challenge has the propensity to become viral among smokers who have the guts to light up in public. However, there is no underlying good to society coming from the challenge and it remains illegal even in states where marijuana is legal. Although we must admit the video did get a chuckle from our staff, we don’t condone this behavior as it hinders the efficacy of legalization, and certainly would offend those who don’t want to be around the drug or have children in their presence. ", slug: "loud-challenge-smoke-weed-in-public", source: "https://www.whaxy.com/news/loud-challenge-smoke-weed-in-public", media: "@whaxy", author: "Whaxy Staff", email: "whaxy.cc@gmail.com", is_draft: false, is_public: true})
